version: "3.7"
services:
  app:
    build: ./app
    ports:
      - 5000:5000
    env_file:
      - .env
    command:
      python -u app.py
    depends_on:
      - postgres

  postgres:
    image: "postgres:alpine"
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: