version: "3.7"
services:
  app:
    build: ./app
    ports:
      - 8000:8000
    env_file:
      - .env
    command:
      gunicorn 'app:run_app()' --chdir /usr/src/ -b 0.0.0.0:8000 --access-logfile - --reload --reload-extra-file /usr/src/templates/
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/src

  postgres:
    image: "postgres:alpine"
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: